# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mingu Kwak
title: ML Engineer & MLOps Engineer
email: deokgu1994@gmail.com
website: deokgu94.tistory.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  deokgu94
facebook_username: "100076592190487"
instagram_username: deokgu94
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# flickr_username: jekyll
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Portfolio
  icon: fas fa-paperclip
  url: https://water-gear-ab4.notion.site/MinguKwak-cb5ef7620bb344d1b8b97af0160092ff
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/resize.png
about_content: | # this will include new lines to allow paragraphs
  계속해서 좋은 코드, 빠르고 정확한 코드를 작성하기 위해 찾고, 배우는 것을 좋아하는 곽민구입니다.
  <br><br>

  QA로 작성된 코드에서 버그를 찾아가며 탄탄한 검증을 통해 완성되어 가는 코드를 수정하고 배웠습니다.
  또한, Field Engineer로 사무실에서 미처 생각하지 못했던 것을 현장 경험을 통해 느꼈습니다.

  이제 경험했던 것을 잘 활용해서 더 좋은 프로그램을 만드는 개발자가 되고 싶습니다.
  <br><br>

  저는 ML 경량화, MLOps, 자율 주행, Embedded에 관심 있습니다.

content:
  - title: Employment # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <br>(주)시스윈일렉트로닉스
        link: http://www.syswin.co.kr/html/
        sub_title: Python, C++, Linux
        caption: 2020.5 ~ 2021.08
        # link_text: boringcompany.com
        quote: >
          Field Engineer, Tester(H/W, S/W)
        description: | # this will include new lines to allow paragraphs
            - PCS, IOT Box, AGV 현장 대응 및 사이드 이펙트 분석<br>

      - layout: left
        title: <br>(주)오토소프트
        link: https://blog.naver.com/autosoft2012
        sub_title:  Python, C/C++, Linux, Embedded<br>CAN, PySide2, MISRA C,
        caption: 2017.10 ~ 2020.03
        # link_text: boringcompany.com
        quote: >
          S/W Engineer, S/W QA
        description: | # this will include new lines to allow paragraphs
            - AMP Code 개발
            - **MDPS 고장 진단 테스트 자동화 프로그램 제작**
            - MDPS Gen3, Gen4 Modle Flash Tun 생성 코드 개발 관리
            - SWDR 리포트 업무 자동화 프로그램 제작 
            - 자동차 Gen3, Gen4 Model 오디오 S/W QA<br><br>


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <br>Final Project<br>간편한 식단관리 FoodLog
        sub_title: 부스트캠프 AI Tech 2기
        link: https://stages.ai/
        caption: 2021.12 ~ 2021.12
        additional_links:
          - title: 간편한 식단관리 FoodLog
            icon: fab fa-github
            url: https://github.com/boostcampaitech2/final-project-level3-cv-09
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          - DVC를 통해 <mark>데이터 버전 관리</mark>
          - 모델링(yolov5, MMdetection(faster_rcnn))

      - layout: left
        title: <br>National Pathology Health Datathon 2021
        sub_title: 국립암센터, Nphd2021
        link: http://nphd2021.co.kr/
        caption: 2021.11 ~ 2021.11
        additional_links:
          - title: B-Track(세포 병리이미지) Classification
            icon: fab fa-github
            url: https://github.com/deokgu94/data-ton
        quote: >
          세포 병리 이미지에서 양성, 음성을 분류하는 Competition
        description: | # this will include new lines to allow paragraphs
          - 이전에 작성하고 있던 Pytorch-Template를 수정하여 팀의 Base Code를 제공
          - Debug 모드를 통해서 빠르게 코드 에러 및 간단한 지표를 확인하는 코드 추가
          - <mark>Wandb</mark>를 통해서 모델 결과 관리, Augmentation을 분석함
          - <mark>MultilabelStratifiedKFold</mark> 적용 후 사용<br>

      - layout: left
        title: <br>재활용 품목 분류 Semantic Segmentation
        sub_title: 부스트캠프 AI Tech 2기  
        caption: 2021.10 ~ 2021.11
        link: https://stages.ai/
        additional_links:
          - title: 재활용 품목 분류를 위한 Semantic Segmentation
            icon: fab fa-github
            url: https://github.com/deokgu/semantic-segmentation-level2-cv-09
        quote: >
          재활용품 사진에 대해서 10개의 클래스 분류하는 Competition
        description: | # this will include new lines to allow paragraphs
          - [MMSegmentation](https://github.com/open-mmlab/mmsegmentation)을 활용
          - 제공되는 Optimizer 대신에 최근 논문에 기재된 Optimizer(RAdam, AdamP)를 사용하여 성능 향상에 기여<br>
      
      - layout: left
        title: <br>재활용 품목 분류 Object Detection
        sub_title: 부스트캠프 AI Tech 2기  
        caption: 2021.9 ~ 2021.10
        link: https://stages.ai/
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: 재활용 품목 분류를 위한 Object Detection
            icon: fab fa-github
            url: https://github.com/deokgu/object-detection-level2-cv-09
        quote: >
          재활용품 사진에 대해 10개의 클래스 분류하는 Competition
        description: | # this will include new lines to allow paragraphs
          - [MMDetection](https://github.com/open-mmlab/mmdetection)을 활용
          - 제공되는 모델 대신에 조금 더 큰 데이터에 Pre trained 된 모듈을 사용해서 성능 향상에 기여<br>

      - layout: left
        title: <br>마스크 착용 상태 분류
        sub_title: 부스트캠프 AI Tech 2기  
        caption: 2021.8 ~ 2021.09
        link: https://stages.ai/
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  마스크 착용 상태분류
            icon: fab fa-github
            url: https://github.com/deokgu94/image-classification-level1-23
        quote: >
          사람에 따른 마스크 이미지로 Mask, Age, Gender 별 클래스 분류하는 Competition
        description: | # this will include new lines to allow paragraphs
          - [Pytorch-Template](https://github.com/victoresque/pytorch-template)을 수정하여 <mark>Stratified k-fold</mark>, <mark>Multi-Label</mark> 추가, Base Code로 사용 및 최종 제출<br><br>


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # - layout: left
      #   title: <br>패스트 캠퍼스<br>수학적으로 접근하는 딥러닝
      #   caption:  2021.12 ~ 2021.12
      #   link: https://fastcampus.co.kr/data_online_mathdeep
      #   quote: >
      #     딥러닝, 회귀 모델
      #   description: | # this will include new lines to allow paragraphs
      #     - 딥러닝을 진행하면서 수학에 대한 이해없이 바로 코드를 활용하여 수학적으로 접근해보고자 참여<br>

      - layout: left
        title: <br>인프런<br>머신러닝 엔지니어 실무
        caption:  2021.08 ~ 2021.10
        link: https://inf.run/y1MY
        quote: >
          실무 기반의 AI Production
        description: | # this will include new lines to allow paragraphs
          - 머신러닝을 실무에 적용한다면 어떻게 진행 되는지 이해함
          - 머신러닝 프로젝트의 기술들을 이해함
          - Kubeflow, mlflow, bentoML<br>

      - layout: left
        title: <br>네이버 커넥트재단 부스트캠프<br> AI Tech 2기
        caption:  2021.08 ~ 2021.12
        link: https://boostcamp.connect.or.kr/
        additional_links:
          - title: 부스트캠프 AI Tech 2기 
            icon: fab fa-github
            url: https://github.com/boostcampaitech2/Overview?fbclid=IwAR1UCo--kzq214H7mV_yutrF_FrR_ENmJIdQCUxwOWSl0fLtvlRI3kqjbjA
        quote: >
            인공지능, 딥러닝 활용 방법과 AI Production의 End-to-End 교육 프로그램
        description: | # this will include new lines to allow paragraphs
          - <mark>Image Classfication</mark> Competition
          - <mark>Object-Detection</mark> Competition
          - <mark>Semantic Segmentation</mark> Competition
          - <mark>Optimization</mark> Competition
          
          - Product Serving - <mark>MLOps</mark><br><br>

      - layout: left
        title: <br>한국전자정보통신산업진흥회<br>임베디드 커널 및 객체지향 코드 기법 향상 과정 
        caption:  2019.12.02 ~ 2019.12.04
        additional_links:
          - title: 임베디드 커널 및 객체지향 코드 기법 향상 과정 
            icon: fab fa-internet-explorer
            url: https://www.hrd.go.kr/hrdp/co/pcobo/PCOBO0100P.do?tracseId=ABB20193000622635&tracseTme=2&crseTracseSe=C0042&trainstCstmrId=500020050311#undefined
        quote: >
          커널 소스 분석 환경 준비, 커널 소스 분석 등을 수행하는 능력 함양
        description: | # this will include new lines to allow paragraphs
          - C/C++ 코드가 ARM Processor에서 실행되는 과정들을 이해함
          - C++ 코드를 C언어기반 객체지향 코드로 구현하는 기법을 습득

        
  - title: Skill & License
    layout: list
    content: # this will include new lines to allow paragraphs
      - layout: left
        title: Library
        # link_text: boringcompany.com
        description: | # this will include new lines to allow paragraphs
          - Pytorch
          - Docker, Kubernetes, Kubeflow, bentoML
          - Git, DVC
          - Pandas, Numpy 
          - Matplotlib, Wandb
          - Jinja2, CAN, PySide2

      - layout: left
        title: Language
        description: | # this will include new lines to allow paragraphs
          - Python
          - C/C++      
          - CAPL
      
      - layout: left
        title: License
        description: | # this will include new lines to allow paragraphs
          - ISTQB(CTFL)


  - title: More
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Today I Learned](https://water-gear-ab4.notion.site/0654cc1f1ce442c98f34103cea771e20?v=7626107d9c0a46e1bfd843789d5b55a6)
      - [CV](https://deokgu94.github.io/) & [Portfolio](https://water-gear-ab4.notion.site/MinguKwak-cb5ef7620bb344d1b8b97af0160092ff)
      - 이력서 양식: [참고](https://jojoldu.github.io/) & [Fork github](https://github.com/sproogen/modern-resume-theme)


# Footer
footer_show_references: False
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 